const pokemonArray = [
    {
        name:"Bulbasaur",
        type:"grass/poison",
        number:"001",
        image:"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
        isCool: true,
        height: "2 ft. 4 in.",
        weight: "15.2 lbs.",
        abilities: "Overgrow",
    },
    {
        name:"Ivysaur",
        type:"grass/poison",
        number:"002",
        image:"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/002.png",
        isCool: true,
        height: "3 ft. 3 in.",
        weight: "28.7 lbs.",
        abilities: "Overgrow",
    },
    {
        name:"Venusaur",
        type:"grass/poison",
        number:"003",
        image:"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png",
        isCool: true,
        height: "6 ft. 7 in.",
        weight: "220.5 lbs.",
        abilities: "Overgrow",
    },
    {
        name:"Charmander",
        type:"fire",
        number:"004",
        image:"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png",
        isCool: true,
        height: "2 ft. 4 in.",
        weight: "15.2 lbs.",
        abilities: "Overgrow",
    },
    {
        name:"Charmeleon",
        type:"fire",
        number:"005",
        image:"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/005.png",
        isCool: true,
        height: "2 ft.",
        weight: "18.7 lbs.",
        abilities: "Blaze",
    },
    {
        name:"Charizard",
        type:"fire/flying",
        number:"006",
        image:"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png",
        isCool: true,
        height: "5 ft. 7 in.",
        weight: "199.5 lbs.",
        abilities: "Blaze",
    },
    {
        name:"Squirtle",
        type:"water",
        number:"007",
        image:"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png",
        isCool: true,
        height: "1 ft. 8 in.",
        weight: "19.8 lbs.",
        abilities: "Torrent",
    },
    {
        name:"Wartortle",
        type:"water",
        number:"008",
        image:"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/008.png",
        isCool: true,
        height: "3 ft. 3 in.",
        weight: "49.6 lbs.",
        abilities: "Torrent",
    },
    {
        name:"Blastoise",
        type:"water",
        number:"009",
        image:"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/009.png",
        isCool: true,
        height: "5 ft. 3 in.",
        weight: "188.5 lbs.",
        abilities: "Torrent",
    },
    {
        name:"Caterpie",
        type:"bug",
        number:"010",
        image:"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/010.png",
        isCool: true,
        height: "1 ft.",
        weight: "6.4 lbs.",
        abilities: "Shield Dust",
    },
]

module.exports = pokemonArray